# Generated by Django 3.0.3 on 2020-04-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='portfolio',
            new_name='Project',
        ),
    ]
